FROM debian:jessie

RUN apt-get update && apt-get install -y \
      gcc \
      make \
      libcunit1 \
      libcunit1-doc \
      libcunit1-dev

CMD cd sources && gcc -o run_tests tests/*.c  -lcunit -std=c99 -fsanitize=address && ./run_tests && rm run_tests